# Generated by Django 2.2 on 2019-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Image')),
                ('description', models.CharField(max_length=1024, verbose_name='Description of Image')),
                ('horizontal_image', models.URLField(blank=True, verbose_name='Horizontal Image')),
                ('vertical_image', models.URLField(blank=True, verbose_name='Vertical Image')),
                ('horizontal_small_image', models.URLField(blank=True, verbose_name='Horizontal Small Image')),
                ('gallery', models.URLField(blank=True, verbose_name='Gallery')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Added On')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified On')),
            ],
        ),
    ]
