"""
Django settings for Image project.

Generated by 'django-admin startproject' using Django 1.11.20.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from celery import Celery

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8l9h%k5iqx7h2qb)pf77^!ts^ey8_69a*kw0ydjl0*x9%dqu)7'

# SECURITY WARNING: don't run with debug turned on in production!
CONSTNT = 'https://s3.ap-south-1.amazonaws.com/myinsiderimagebucket/my_image.jpg'
CONSTANT = 'https://s3.ap-south-1.amazonaws.com/myinsiderimagebucket'
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'image_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Image.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Image.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


# CELERY CONFIGURATION
CELERY_BROKER_URL = 'redis://localhost'

# AWS configuration
BUCKET_DOMAIN = 'https://s3.ap-south-1.amazonaws.com/myinsiderimagebucket/'
S3_DOMAIN = 's3-website.ap-south-1.amazonaws.com'
AWS_ACCESS_KEY_ID = 'AXXXXXXXXXX'
AWS_SECRET_ACCESS_KEY = 'JXXXXXXXXXXXXXXXXXXXXXXXXXX'
AWS_STORAGE_BUCKET_NAME = 'myinsiderimagebucket'
AWS_LOCATION = 'ap-south-1'
AWS_S3_CUSTOM_DOMAIN = 's3.%s.amazonaws.com' % AWS_LOCATION


AWS_BUCKETS_CONFIG = {
    AWS_STORAGE_BUCKET_NAME: {
        'access_key_id': AWS_ACCESS_KEY_ID,
        'secret_access_key': AWS_SECRET_ACCESS_KEY,
        'username': 'samrat.orthodox@gmail.com'
    }
}


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'media/images'),
]


STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)

DEFAULT_BUCKET = 'myinsiderimagebucket'
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jfif', 'jif', 'png', 'gif', 'jpeg']

